{% set name = "psdaq" %}
{% set version = "3.3.24" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/slac-lcls/lcls2/archive/refs/tags/{{ version }}.tar.gz
  sha256: 6a415cefaa87a516935512c5768219a5e6f8856a8a0ba8d6845d5f78f53a6f61

build:
  skip: True  # [win or osx]
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ cdt('libibverbs') }}
    - {{ cdt('libibverbs-devel') }}
    - {{ cdt('libnl') }}
    - {{ cdt('librdmacm') }}
    - {{ cdt('librdmacm-devel') }}
    - {{ cdt('libudev') }}
    - {{ cdt('libudev-devel') }}
    - make
    - cmake
  host:
    - python
    - setuptools
    - pip
    - xtcdata
    - psalg
    - python
    - libfabric
    - epics-base
    - prometheus-cpp
    - rapidjson
    - readline
    - zeromq
    - p4p
    - zlib
    - libusdusb4
    - libusb
  run:
    - python
    - xtcdata
    - psalg
    - python
    - libfabric
    - rapidjson
    - readline
    - transitions
    - requests
    - zeromq
    - prometheus-cpp
    - prometheus_client
    - amityping
    - mypy
    - rogue
    - bluesky
    - ophyd
    - p4p
    - lcls2_timetool
    - epics-base
    - zlib
    - libusdusb4
    - posix_ipc

about:
  home: https://github.com/slac-lcls/lcls2
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.md
  summary: 'LCLS-II DAQ and Software'
  description: |
    DAQ and analysis software for LCLS-II
  doc_url: https://github.com/slac-lcls/lcls2 
  dev_url: https://github.com/slac-lcls/lcls2

extra:
  recipe-maintainers:
    - valmar
    - chrisvam

